#!/bin/bash

if [[ "$1" != "-f" ]];then
    counter_dir="$HOME/.config/librazik"
    counter_file="$counter_dir/start_counter"

    if [ ! -f "$counter_file" ];then
        mkdir -p "$counter_dir" || exit 1
        start_counter=0
        echo "$start_counter" > "$counter_file" || exit 2
    else
        start_counter=$(cat "$counter_file")
        $(let "$start_counter") || start_counter=0
    fi
    echo "$(($start_counter+1))" > "$counter_file" || exit 3
    [ $(($start_counter % 30)) != 15 ] && exit 0
fi

INSTALL_PREFIX="X-PREFIX-X"
exec "$INSTALL_PREFIX/share/librazik-donatetip/src/lzk_donate_tip.py" "$@" 
